version: '3'
services:
   database:
     image: postgres:12.3-alpine
     volumes:
       - application-data:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=coloniaDB
       - POSTGRES_USER=factoria2020
       - POSTGRES_PASSWORD=Un.p4n0l.par4.fact0ri@
     networks:
      - backendNetwork
   
   servicio:
    build: ./coloniaweb
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=database
      - POSTGRES_DB=coloniaDB
      - POSTGRES_USER=factoria2020
      - POSTGRES_PASSWORD=Un.p4n0l.par4.fact0ri@
    networks:
      - backendNetwork
      - frontendNetwork
      
   nginx-proxy:
     image: jwilder/nginx-proxy
     restart: always
     ports:
       - "80:80"
#       - "443:443"
#     volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - certs:/etc/nginx/certs:ro
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#     labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
       
#   letsencrypt:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#     restart: always
#     environment:
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#     volumes:
#      - certs:/etc/nginx/certs:rw
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - /var/run/docker.sock:/var/run/docker.sock:ro

   cliente:
     build: ./front-end
     restart: always
     expose:
       - "80"
     volumes:
       - /home/colonia/colonia/front-end:/usr/src/app
     environment:
       - VIRTUAL_HOST=investigacionlacolonia.com,www.investigacionlacolonia.com
#       - LETSENCRYPT_HOST=investigacionlacolonia.com,www.investigacionlacolonia.com
#       - LETSENCRYPT_EMAIL=alfonso@investigacionlacolonia.com
     networks:
      - frontendNetwork
       
volumes:
  application-data:
#  certs:
#  vhostd:
#  html:
  
networks:
  backendNetwork:
  frontendNetwork: